@echo off
echo Ejecutando Canon Técnico Sellado con elevación...
powershell -Command "Start-Process powershell -ArgumentList '-ExecutionPolicy Bypass -File D:\Evie-of-the-Mental-Weave\scripts\canon-tecnico-limpiador.ps1' -Verb RunAs -Wait"
echo Proceso completado. Presiona cualquier tecla para continuar...
pause >nul